name: Anyconnect创建NoRoute路由表
on:
  push:
    branches: 
      - master
  schedule:
    - cron: '* */7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
          
      - name: 'Install pip'
        run: |
             pip install requests 
             pip install netaddr
       
      - name: 'Build NoRoute'
        run: |
             cd Anyconnect/build
             python NoRoute_build.py
             ls -al
      - name: Push changes
        uses: ad-m/github-push-action@build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

