name: Anyconnect创建NoRoute路由表
on:
  push:
    branches: 
      - master
  schedule:
    - cron: '* */7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
          
      - name: 'Install pip'
        run: |
             pip install requests 
             pip install netaddr
       
      - name: 'Build NoRoute'
        run: |
             cd Anyconnect/build
             wget -N http://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-extended-latest
             wget -N http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-extended-latest
             wget -N http://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest
             wget -N http://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-extended-latest
             wget -N http://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-extended-latest
             cat delegated-afrinic-extended-latest delegated-apnic-extended-latest delegated-arin-extended-latest delegated-lacnic-extended-latest delegated-ripencc-extended-latest>>delegated-all-latest
             cat delegated-all-latest | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' >chnroute.txt
             python NoRoute_build.py
             ls -al
      - name: push
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish'
          force-add: 'true'
          files: Anyconnect/build/cn-no-route1.txt Anyconnect/build/cn-no-route2.txt 
          name: upgrade
          email: pengxp1996@hotmail.com

