name: Anyconnect创建NoRoute路由表
on:
  push:
    branches: 
      - master
  schedule:
    - cron: '* */7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
          
      - name: 'Build'
        run: |
             cd Anyconnect/build
             pip install requests netaddr
             python NoRoute_build.py
        


