name: Build Ocserv Noroute
on:
  push:
    branches: 
      - master
  schedule:
    - cron: '30 9 */7 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
          
      - name: 'Install pip'
        run: |
             pip install requests 
             pip install netaddr
       
      - name: 'Build NoRoute'
        run: |
             cd Anyconnect/build
             python NoRoute_build.py

      - name: push
      - uses: github-actions-x/commit@v2.8
       with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'publish'
        force-add: 'true'
        files: Anyconnect/build/cn-no-route1.txt Anyconnect/build/cn-no-route2.txt 
        name: commiter name
        email: pengxp1996@hotmail.com 
